services:
  db:
    image: postgres
    container_name: cpbattles-db
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  jobs:
    image: mongo
    container_name: cpbattles-jobs
    ports:
      - "27017:27017"
    volumes:
      - jobs_data:/data/db

volumes:
  db_data:
  jobs_data:
